name = "prototype"
main = "index.js"
account_id = "2952a38a59e8d419aefa3c409c5cdf3a"
compatibility_date = "2026-01-30"
[durable_objects]
bindings = [
   { name = "CHAT_ROOM", class_name = "ChatRoom" }
]
   
[[migrations]]
    tag = "v2"
    new_sqlite_classes = ["ChatRoom"]